### ISSUE TITLE
Compiler doesn't recognise classpath jars

### ISSUE THREAD

**Issue by PranavPurwar** [itsaky/nb-javac-android#1]
Upon running it on a test app, the nb-javac-android compiler complains of no classpath containing java.lang.* class files even tho it is present whereas nb-javac from CodeAssist (again with the same arguments) works fine. This seems like an issue with scanning jar files?

**Comment by itsaky** [comment]
First of all, the version of nb-javac was built with `AndroidIDE` in mind. So it is different from the version that CodeAssist uses.

To get this javac working with your project, you have to generate a minimal JDK with only the classes from android.jar and then use it with this nb-javac-android. You can use [`androidide-jdk-transform`](https://github.com/itsaky/androidide-jdk-transform) to generate such JDK images.

Apart from this, this nb-javac has names of classes from AndroidIDE hardcoded in it. For example, it uses the [`Environment` ](https://github.com/itsaky/AndroidIDE/blob/main/common/src/main/java/com/itsaky/androidide/utils/Environment.java) class to get the path to the transformed JDK image as seen [here](https://github.com/itsaky/nb-javac-android/blob/53e798294a1778084c4c8a4d2145e54ed4467365/src/jdk.compiler/share/classes/jdk/internal/jrtfs/SystemImage.java#L95).

**Comment by itsaky** [comment]
This is clearly not a bug. It is just how this `nb-javac-android` is designed.

**Comment by PranavPurwar** [comment]
No issues, i didn't knew that earlier as it was published on maven.

**Comment by PranavPurwar** [comment]
Thanks! It's working now after creating the com.itsaky.androidide.utils.Environment file with a static field containing the system modules path. However, I think It'd be more convenient to set up if the class path is not hardcoded/is changeable

**Comment by itsaky** [comment]
You can now configure `nb-javac-android` to use a custom `JAVA_HOME` without creating the `Environment` class. Simply set the `androidide.java.home` property with `System.setProperty(String, String)`. Use the `PROP_ANDROIDIDE_JAVA_HOME` field in `JavacConfigProvider`

See [`JavacConfigProvider`](https://github.com/itsaky/nb-javac-android/blob/main/src/jdk.compiler/share/classes/com/itsaky/androidide/config/JavacConfigProvider.java) for more detail.

**Comment by itsaky** [comment]
This will be available in release `17.0.0.2` which will take few minutes to get published.
